kal: milestone, ics data can be added to the calendar

diff --git a/tests/_setup_alias b/tests/_setup_alias
--- a/tests/_setup_alias
+++ b/tests/_setup_alias
@@ -1,3 +1,5 @@
+outfile=$(mktemp)
+
 error() {
     echo "$1"
     echo "sleeping 3"
@@ -9,10 +11,18 @@ error() {
 [ -z "$calendar_cli" ] && [ -x ../calendar-cli.py ] && calendar_cli=../calendar-cli.py
 [ -z "$calendar_cli" ] && error "couldn't find ./calendar_cli.py nor ../calendar_cli.py"
 
+[ -z "$kal" ] && [ -x ./cal.py ] && kal=./cal.py
+[ -z "$kal" ] && [ -x ../cal.py ] && kal=../cal.py
+[ -z "$kal" ] && error "couldn't find ./cal.py nor ../cal.py"
+
 calendar_cli() {
     echo "    $calendar_cli $@"
-    output=$($calendar_cli "$@")
-    [ -z "$output" ] || echo $output
+    output=$($calendar_cli "$@" | tee $outfile)
+    [ -z "$output" ] || [ -z "$QUIET" ] || echo $output
 }
 
-## TODO: new kal command aka cal.py
+kal() {
+    echo "    $kal $@"
+    output=$($kal "$@"  | tee $outfile)
+    [ -z "$output" ] || [ -z "$QUIET" ] || echo $output
+}
